### ISSUE TITLE
java.lang.Throwable: Can't remove document listener on Pycharm 

### ISSUE THREAD

**Issue by tungph** [sourcery-ai/sourcery#391]
I've got this exception 4 times for the last 4 days, but not sure how to reproduce it.

```
java.lang.Throwable: Can't remove document listener (org.wso2.lsp4intellij.editor.DocumentEventManager@1fca5c7). Registered listeners: [com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1@538d52da, 362, 0, Multicaster, Multicaster, com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$1@50a98b7d]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.openapi.editor.impl.DocumentImpl.removeDocumentListener(DocumentImpl.java:995)
	at org.wso2.lsp4intellij.editor.DocumentEventManager.documentClosed(DocumentEventManager.java:137)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Debug Information

IDE Version: 
PyCharm 2023.2.1 (Professional Edition)
Build #PY-232.9559.58, built on August 22, 2023
Runtime version: 17.0.8+7-b1000.8 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Sourcery Version: 
Sourcery 1.10.0

Operating system and Version:
MacOS Sonoma 14.0 (23A344)

**Comment by brendanator** [comment]
Thanks for reporting this @tungph - I'm investigating right now

**Comment by brendanator** [comment]
I haven't been able to reproduce this either. However, I've made a change that should hopefully stop it from happening. It will be in the release coming out mid next week

**Comment by tungph** [comment]
@brendanator, I appreciate the update. I updated Sourcery to 1.10.1, but the problem persisted. 
<img width="824" alt="image" src="https://github.com/sourcery-ai/sourcery/assets/4607414/9adc5242-3fa7-400f-a6bb-897c30767900">

I would be happy to assist if there was a method to obtain additional debug information on this fault.

**Comment by brendanator** [comment]
Thanks for this @tungph 

They are slightly different issues. I have put in an additional change to try and fix this too. Let me know how you get on when it is released later this week

**Comment by Hellebore** [comment]
Should be addressed with release of 1.11.0 - @tungph please let us know if this or similar issues do pop up.

**Comment by tungph** [comment]
<img width="1106" alt="image" src="https://github.com/sourcery-ai/sourcery/assets/4607414/fa2e6375-72fa-4f3d-a736-e89fcb2597de">

The issue is still occurring in version 1.11.0 as well.

**Comment by tungph** [comment]
<img width="1106" alt="image" src="https://github.com/sourcery-ai/sourcery/assets/4607414/006bbd8f-0155-475a-80bf-0be67841aa92">
