### ISSUE TITLE
Config file schema's `python_version` does not match the format provided in documentation

### ISSUE THREAD

**Issue by tylerlaprade** [sourcery-ai/sourcery#432]
### Checklist

- [x] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [x] I have read the common issues and fixes listed in the [Sourcery troubleshooting page](https://docs.sourcery.ai/Product/Troubleshooting/#troubleshooting), and found nothing
- [x] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description
<img width="949" alt="image" src="https://github.com/user-attachments/assets/cabf9f38-eeb8-44a1-962c-e0e7d0f72902">

https://docs.sourcery.ai/resources/sourcery_yaml_schema.json

https://docs.sourcery.ai/Coding-Assistant/Reference/Configuration/sourcery-yaml/

**Comment by ruancomelli** [comment]
Hey, @tylerlaprade!

I've just merged a fix for this, and it will be available in the next Sourcery release.

Thanks for opening this issue!

**Comment by tylerlaprade** [comment]
Hi @ruancomelli, thanks for the fix. I'm still getting an error, it's just with a different message now:

<img width="632" alt="Image" src="https://github.com/user-attachments/assets/e6e69917-33b0-4256-95b3-9f9db5a6ac74" />

**Comment by tylerlaprade** [comment]
Hi @Hellebore , checking in on this. I couldn't find where this schema is defined in the code, so I didn't open a PR myself. I believe I've identified the issue, though. In [the schema](https://docs.sourcery.ai/resources/sourcery_yaml_schema.json), `python_version` is defined with `"type": "union"`. As per [this answer](https://stackoverflow.com/a/61225670), it should actually be an array of the allowable types. Or it's possible that line can just be omitted and the types will be inferred from the actual union, if so, that's even better because it forces the type to match the actual definition.
